/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PROJECT CAR90 (https://sketchfab.com/samuelcarvalho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/land-rover-defender-edition-grasmere-green-b7596dc0abc749c3b076d1f830715a54
Title: Land Rover Defender - Edition Grasmere Green
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';
import gsap from 'gsap'

export function Model({isMobile,scale, scrollState, inViewport, ...props}) {

  const timeline = useRef();
  const wheelRef = useRef();
  const Inner2Ref = useRef();
  const upperGlass = useRef();
  const camera = useThree((state) => state.camera);


  const generalGroupRef = useRef();

  const page_1_ref = useRef();
  const page_2_ref = useRef();
  const page_3_ref = useRef();
  const page_4_ref = useRef();
  const page_5_ref = useRef();
  // const page_6_ref = useRef();

  useLayoutEffect(() => {
    page_1_ref.current = document.getElementById("page-1");
    page_2_ref.current = document.getElementById("page-2");
    page_3_ref.current = document.getElementById("page-3");
    page_4_ref.current = document.getElementById("page-4");
    page_5_ref.current = document.getElementById("page-5");
    // page_6_ref.current = document.getElementById("page-6");
  }, []);

  useLayoutEffect(() =>{
    
    timeline.current = gsap.timeline();
    let AnimationsData = [];

    const DefenderAnimations = [
        {
            // Html div
            // Restore previous animations
            objectToAnimate: page_1_ref.current,
            properties: {
              opacity: 0,
              duration: 0.3,
            },
            timelinePoint: 0.8,
          },
        {
            objectToAnimate: page_2_ref.current,
            properties: {
              opacity: 1,
              duration: 0.8,
            },
            timelinePoint: 1.3,
          },
        {
            objectToAnimate: generalGroupRef.current.position,
            properties:{
                x:2.5,
                y:-2.5,
                z:7.5,
                duration:0.8,
            },
            timelinePoint:1

        },
        {
            objectToAnimate: generalGroupRef.current.rotation,
            properties:{
                x:0,
                y:0.3,
                duration:0.8,
            },
            timelinePoint:1

        },
      {
        objectToAnimate: camera.position,
        properties: {
          x: 0,
          y:0.2097,
          z: 5.3,
          duration: 0.8,
        },
        timelinePoint: 1,
      },
      {
        objectToAnimate: camera,
        properties: {
          zoom: 1.5,
          duration: 0.8,
          onUpdate: () => {
            camera.updateProjectionMatrix();
          },
        },
        timelinePoint: 1,
      },
    ];

    AnimationsData = [
      ...AnimationsData,
      ...DefenderAnimations,
    ];

    const TopAnimations = [
        {
            objectToAnimate: page_3_ref.current,
            properties: {
              opacity: 0,
              duration: 0.3,
            },
            timelinePoint: 3.2,
          },
    
          //html div
          {
            objectToAnimate: page_4_ref.current,
            properties: {
              opacity: 1,
              duration: 0.3,
            },
            timelinePoint: 3.3,
          },
        // controls, camera, camera zoom
        {
          objectToAnimate: camera.position,
          properties: {
            x: 0,
            y: 0,
            z: 8.3,
            duration: 0.8,
          },
          timelinePoint: 3,
        },
        {
          objectToAnimate: camera,
          propertines: {
            zoom: 1.2,
            duration: 0.8,
            onUpdate: () => {
              camera.updateProjectionMatrix();
            },
          },
          timelinePoint: 3,
        },
        // General groups
        {
            objectToAnimate: generalGroupRef.current.rotation,
            properties: {
              x: 0,
              y: -1.7,
              z: -1.4,
              duration: 0.8,
            },
            timelinePoint: 3,
          },
          {
            objectToAnimate: generalGroupRef.current.position,
            properties: {
              x: -0.4,
              y: -0.4,
              z: -2,
              duration: 0.8,
            },
            timelinePoint: 3,
          },
  
        // Battery cover
      ];

    AnimationsData = [
        ...AnimationsData,
        ...TopAnimations,
    ];
    const RightSideAnimation = [

         // Restore previous animations
      {
        objectToAnimate: page_2_ref.current,
        properties: {
          opacity: 0,
          duration: 0.3,
        },
        timelinePoint: 2.1,
      },

      //html div
      {
        objectToAnimate: page_3_ref.current,
        properties: {
          opacity: 1,
          duration: 0.3,
        },
        timelinePoint: 2.3,
      },

          {
            objectToAnimate: camera.position,
            properties: {
              x: 0,
              y: 0,
              z: 8.3,
              duration: 0.8,
            },
            timelinePoint: 2,
          },
          {
            objectToAnimate: camera,
            properties: {
              zoom: 1.3,
              duration: 0.3,
              onUpdate: () => {
                camera.updateProjectionMatrix();
              },
            },
            timelinePoint: 2.3,
          },
          // General group
          {
            objectToAnimate: generalGroupRef.current.rotation,
            properties: {
              x: 0.1,
              y: -1,
              z: 0,
              duration: 0.8,
            },
            timelinePoint: 2.1,
          },
          {
            objectToAnimate: generalGroupRef.current.position,
            properties: {
              x: 4,
              y: -2,
              z: 0,
              duration: 0.8,
            },
            timelinePoint: 2.1,
          },
    ]

    AnimationsData = [
        ...AnimationsData,
        ...RightSideAnimation,
    ];

    const TyreAnimation = [
        {
            objectToAnimate: page_4_ref.current,
            properties: {
              opacity: 0,
              duration: 0.3,
            },
            timelinePoint: 4.1,
          },
          // Html div
          {
            objectToAnimate: page_5_ref.current,
            properties: {
              opacity: 1,
              duration: 0.8,
            },
            timelinePoint: 4.6,
          },
        
        // Controls, Camera and Camera Zoom
       
        {
          objectToAnimate: camera.position,
          properties: {
            x: 0,
            y: 0,
            z: 8.3,
            duration: 0.8,
          },
          timelinePoint: 4,
        },
        {
          objectToAnimate: camera,
          properties: {
            zoom: 1,
            duration: 0.8,
            onUpdate: () => {
              camera.updateProjectionMatrix();
            },
          },
          timelinePoint: 4.3,
        },
  
        // General group
        {
          objectToAnimate: generalGroupRef.current.rotation,
          properties: {
            x: 0,
            y: -2.8,
            z: 0,
            duration: 0.8,
          },
          timelinePoint: 4.3,
        },
        {
          objectToAnimate: generalGroupRef.current.position,
          properties: {
            
            x: 2.5,
            y: -2.5,
            z: 5.5,
            duration: 0.8,
          },
          timelinePoint: 4.3,
        },
        
       
      ];
      AnimationsData = [
        ...AnimationsData,
        ...TyreAnimation,
      ];

      const LastAnimation = [
        {
            objectToAnimate: page_5_ref.current,
            properties: {
              opacity: 0,
              duration: 0.3,
            },
            timelinePoint: 5.8,
          },
          // {
          //   objectToAnimate: page_6_ref.current,
          //   properties: {
          //     opacity: 1,
          //     duration: 0.8,
          //   },
          //   timelinePoint: 6.2,
          // },
    
        
        // Controls, Camera, Camera zoom
        {
          objectToAnimate: camera,
          properties: {
            zoom: 1.3,
            duration: 0.8,
            onUpdate: () => {
              camera.updateProjectionMatrix();
            },
          },
          timelinePoint: 5.8,
        },
        {
          objectToAnimate: camera.position,
          properties: {
            x: 0,
            y: 0,
            z: 8.3,
            duration: 0.8,
          },
          timelinePoint: 5.5,
        },
        //General group
        {
          objectToAnimate: generalGroupRef.current.rotation,
          properties: {
            x: 0,
            y: -1.5,
            z: 0,
            duration: 0.8,
          },
          timelinePoint: 5.9,
        },
        {
          objectToAnimate: generalGroupRef.current.position,
          properties: {
            x: 0,
            y: -3,
            z: -2,
            duration: 0.8,
          },
          timelinePoint: 5.9,
        },
    ]

    AnimationsData = [
        ...AnimationsData,
        ...LastAnimation,
    ];

    AnimationsData.map((animation) => {
        timeline.current.to(
            animation.objectToAnimate,{
                ...animation.properties,
                ease: "power4.easeInOut",
            },
            animation.timelinePoint
        );
    })

  },[]) 

    useFrame(()=>{
        timeline.current.seek(scrollState.progress * timeline.current.duration() );
        // console.log(scrollState.progress);
    });
  const { nodes, materials } = useGLTF('/land_rover_defender_-_edition_grasmere_green (1).glb')
  return (
    <>
    <group {...props} scale={0.8} dispose={null}  ref={generalGroupRef}>
      <group
        name="Object153_84"
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}>
        <mesh
          name="Object_172"
          castShadow
          receiveShadow
          geometry={nodes.Object_172.geometry}
          material={materials['Pintura_.002']}
        />
        <mesh
          name="Object_173"
          castShadow
          receiveShadow
          geometry={nodes.Object_173.geometry}
          material={materials['Pintura_.002']}
        />
      </group>
      <group name="Object_61_143" position={[98.024, 3.759, 18.922]} scale={1.545}>
        <mesh
          name="Object_291"
          castShadow
          receiveShadow
          geometry={nodes.Object_291.geometry}
          material={materials['Pintura_.004']}
        />
        <mesh
          name="Object_292"
          castShadow
          receiveShadow
          geometry={nodes.Object_292.geometry}
          material={materials['Pintura_.004']}
        />
      </group>
      <group ref={wheelRef} >
        <mesh
            
            name="Object_34"
            castShadow
            receiveShadow
            geometry={nodes.Object_34.geometry}
            material={materials['Borracha_.001']}
            position={[0, 0.5, 0]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.002}
        />
        <mesh
        name="Object_195"
        castShadow
        receiveShadow
        geometry={nodes.Object_195.geometry}
        material={materials['Pintura_.003']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
       </group>
      <group ref={Inner2Ref}>
      <mesh
      
        name="Object_78"
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_20"
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      </group>
     
      <mesh
        name="Upper Glass"
        castShadow
        receiveShadow
        geometry={nodes.Object_273.geometry}
        material={materials.Vidro_Dispolarizado}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
        ref={upperGlass}
      />
      <mesh
        name="Object_4"
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Vidro_-__Freio']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_6"
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_8"
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_10"
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_12"
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_14"
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_16"
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_18"
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      
      <mesh
        name="Object_22"
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_24"
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_26"
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_28"
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.Cromados}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_30"
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.Cromados}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_32"
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      
      <mesh
        name="Object_36"
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.logo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_38"
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials['Borracha_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_40"
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials['Borracha_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_42"
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials['Borracha_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_44"
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_46"
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_48"
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_50"
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_52"
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_54"
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_56"
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_58"
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_60"
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_62"
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_64"
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_66"
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_68"
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_70"
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_72"
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_74"
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_76"
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      
      <mesh
        name="Object_80"
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_82"
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_84"
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_86"
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_88"
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_90"
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_92"
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_94"
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_96"
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_98"
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_100"
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_102"
        castShadow
        receiveShadow
        color="black"
        geometry={nodes.Object_102.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_104"
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_106"
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_108"
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_110"
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        material={materials.mascara_negra_2}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_112"
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_114"
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_116"
        castShadow
        receiveShadow
        geometry={nodes.Object_116.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_118"
        castShadow
        receiveShadow
        geometry={nodes.Object_118.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_120"
        castShadow
        receiveShadow
        geometry={nodes.Object_120.geometry}
        material={materials['Vidro_-__Freio']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_122"
        castShadow
        receiveShadow
        geometry={nodes.Object_122.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_124"
        castShadow
        receiveShadow
        geometry={nodes.Object_124.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_126"
        castShadow
        receiveShadow
        geometry={nodes.Object_126.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_128"
        castShadow
        receiveShadow
        geometry={nodes.Object_128.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_130"
        castShadow
        receiveShadow
        geometry={nodes.Object_130.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_132"
        castShadow
        receiveShadow
        geometry={nodes.Object_132.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_134"
        castShadow
        receiveShadow
        geometry={nodes.Object_134.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_136"
        castShadow
        receiveShadow
        geometry={nodes.Object_136.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_138"
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_140"
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_142"
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_144"
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_146"
        castShadow
        receiveShadow
        geometry={nodes.Object_146.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_148"
        castShadow
        receiveShadow
        geometry={nodes.Object_148.geometry}
        material={materials.Vidro_Dispolarizado}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_150"
        castShadow
        receiveShadow
        geometry={nodes.Object_150.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_152"
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        material={materials.Vidro_Dispolarizado}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_154"
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_156"
        castShadow
        receiveShadow
        geometry={nodes.Object_156.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_158"
        castShadow
        receiveShadow
        geometry={nodes.Object_158.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_160"
        castShadow
        receiveShadow
        geometry={nodes.Object_160.geometry}
        material={materials.Cromados}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_162"
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        material={materials.Vidro_Dispolarizado}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_164"
        castShadow
        receiveShadow
        geometry={nodes.Object_164.geometry}
        material={materials.Vidro_Dispolarizado}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_166"
        castShadow
        receiveShadow
        geometry={nodes.Object_166.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_168"
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_170"
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials.mascara_negra_2}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_175"
        castShadow
        receiveShadow
        geometry={nodes.Object_175.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_177"
        castShadow
        receiveShadow
        geometry={nodes.Object_177.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_179"
        castShadow
        receiveShadow
        geometry={nodes.Object_179.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_181"
        castShadow
        receiveShadow
        geometry={nodes.Object_181.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_183"
        castShadow
        receiveShadow
        geometry={nodes.Object_183.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_185"
        castShadow
        receiveShadow
        geometry={nodes.Object_185.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_187"
        castShadow
        receiveShadow
        geometry={nodes.Object_187.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_189"
        castShadow
        receiveShadow
        geometry={nodes.Object_189.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_191"
        castShadow
        receiveShadow
        geometry={nodes.Object_191.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_193"
        castShadow
        receiveShadow
        geometry={nodes.Object_193.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      
      <mesh
        name="Object_197"
        castShadow
        receiveShadow
        geometry={nodes.Object_197.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_199"
        castShadow
        receiveShadow
        geometry={nodes.Object_199.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_201"
        castShadow
        receiveShadow
        geometry={nodes.Object_201.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_203"
        castShadow
        receiveShadow
        geometry={nodes.Object_203.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_205"
        castShadow
        receiveShadow
        geometry={nodes.Object_205.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_207"
        castShadow
        receiveShadow
        geometry={nodes.Object_207.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_209"
        castShadow
        receiveShadow
        geometry={nodes.Object_209.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_211"
        castShadow
        receiveShadow
        geometry={nodes.Object_211.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_213"
        castShadow
        receiveShadow
        geometry={nodes.Object_213.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_215"
        castShadow
        receiveShadow
        geometry={nodes.Object_215.geometry}
        material={materials.Cromados}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_217"
        castShadow
        receiveShadow
        geometry={nodes.Object_217.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_219"
        castShadow
        receiveShadow
        geometry={nodes.Object_219.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_221"
        castShadow
        receiveShadow
        geometry={nodes.Object_221.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_223"
        castShadow
        receiveShadow
        geometry={nodes.Object_223.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_225"
        castShadow
        receiveShadow
        geometry={nodes.Object_225.geometry}
        material={materials['Pintura_.003']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_227"
        castShadow
        receiveShadow
        geometry={nodes.Object_227.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_229"
        castShadow
        receiveShadow
        geometry={nodes.Object_229.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_231"
        castShadow
        receiveShadow
        geometry={nodes.Object_231.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_233"
        castShadow
        receiveShadow
        geometry={nodes.Object_233.geometry}
        material={materials['Pintura_.003']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_235"
        castShadow
        receiveShadow
        geometry={nodes.Object_235.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_237"
        castShadow
        receiveShadow
        geometry={nodes.Object_237.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_239"
        castShadow
        receiveShadow
        geometry={nodes.Object_239.geometry}
        material={materials['Pintura_.003']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_241"
        castShadow
        receiveShadow
        geometry={nodes.Object_241.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_243"
        castShadow
        receiveShadow
        geometry={nodes.Object_243.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_245"
        castShadow
        receiveShadow
        geometry={nodes.Object_245.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_247"
        castShadow
        receiveShadow
        geometry={nodes.Object_247.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_249"
        castShadow
        receiveShadow
        geometry={nodes.Object_249.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_251"
        castShadow
        receiveShadow
        geometry={nodes.Object_251.geometry}
        material={materials.Vidro_Dispolarizado}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_253"
        castShadow
        receiveShadow
        geometry={nodes.Object_253.geometry}
        material={materials.mascara_negra}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_255"
        castShadow
        receiveShadow
        geometry={nodes.Object_255.geometry}
        material={materials.Vidro_Dispolarizado}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_257"
        castShadow
        receiveShadow
        geometry={nodes.Object_257.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_259"
        castShadow
        receiveShadow
        geometry={nodes.Object_259.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_261"
        castShadow
        receiveShadow
        geometry={nodes.Object_261.geometry}
        material={materials.wire_000000000}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_263"
        castShadow
        receiveShadow
        geometry={nodes.Object_263.geometry}
        material={materials.Pintura}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_265"
        castShadow
        receiveShadow
        geometry={nodes.Object_265.geometry}
        material={materials.Cromados}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_267"
        castShadow
        receiveShadow
        geometry={nodes.Object_267.geometry}
        material={materials.Plstico_Externo}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_269"
        castShadow
        receiveShadow
        geometry={nodes.Object_269.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_271"
        castShadow
        receiveShadow
        geometry={nodes.Object_271.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      
      <mesh
        name="Object_275"
        castShadow
        receiveShadow
        geometry={nodes.Object_275.geometry}
        material={materials['Vidro_-_Lanterna']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_277"
        castShadow
        receiveShadow
        geometry={nodes.Object_277.geometry}
        material={materials['Vidro_-_Lanterna']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_279"
        castShadow
        receiveShadow
        geometry={nodes.Object_279.geometry}
        material={materials.Cromados}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_281"
        castShadow
        receiveShadow
        geometry={nodes.Object_281.geometry}
        material={materials.Cromados}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_283"
        castShadow
        receiveShadow
        geometry={nodes.Object_283.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_285"
        castShadow
        receiveShadow
        geometry={nodes.Object_285.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_287"
        castShadow
        receiveShadow
        geometry={nodes.Object_287.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_289"
        castShadow
        receiveShadow
        geometry={nodes.Object_289.geometry}
        material={materials['Pintura_.002']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_294"
        castShadow
        receiveShadow
        geometry={nodes.Object_294.geometry}
        material={materials['wire_087224198.001']}
        position={[0.257, 1.729, -4.139]}
        rotation={[1.301, 0, -Math.PI / 2]}
        scale={0.021}
      />
      <mesh
        name="Object_296"
        castShadow
        receiveShadow
        geometry={nodes.Object_296.geometry}
        material={materials['wire_087224198.001']}
        position={[-0.275, 1.583, 4.064]}
        rotation={[1.84, 0, Math.PI / 2]}
        scale={0.021}
      />
      <mesh
        name="Object_298"
        castShadow
        receiveShadow
        geometry={nodes.Object_298.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_300"
        castShadow
        receiveShadow
        geometry={nodes.Object_300.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
      <mesh
        name="Object_302"
        castShadow
        receiveShadow
        geometry={nodes.Object_302.geometry}
        material={materials['Pintura_.001']}
        position={[0, 0.5, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.002}
      />
    </group>
    </>
  )
}

useGLTF.preload('/land_rover_defender_-_edition_grasmere_green (1).glb')